[package]
name = "prolangine"
description = "Programming Language Engine"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "3.0.0"
line-col = "0.2"
strum = { version = "0.26", features = ["derive"] }
unicode-xid = "0.2"
prolangine-macros = { "path" = "src/macros" }
