[package]
name = "yap"
description = "Yet Another Parser"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
line-col = "0.2.1"
once_cell = "1.19.0"
strum = { version = "0.26.2", features = ["derive"] }
unicode-xid = "0.2.4"
